// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eigrkmrdurpuhwkmslcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZ3JrbXJkdXJwdWh3a21zbGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzI3NTcsImV4cCI6MjA2NTQ0ODc1N30.e0U--lh_ZQxdbQbAbVowO2E3Rv--AvmFj5IQzug8K6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);